name: Terraform CI - validate

on:
  [push]

jobs:
  tf_validate:
    name: 'Terraform validate (on tf ${{ matrix.terraform_version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: ['1.1.9', '1.2.9', '1.3.10', '1.4.7', '1.5.7', '1.6.6', '1.7.5']
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: 'Terraform - validate examples/basic'
        working-directory: examples/basic
        run: |
          terraform init
          terraform validate
