name: Terraform CI - validate

on:
  [push]

jobs:
  tf_validate:
    name: 'Terraform validate (on tf ${{ matrix.terraform_version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # oldest supported, a couple intermediates, and latest
        terraform_version: [ '~1.1.0', '~1.5.0', '~1.10.0', 'latest' ]
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: 'Terraform - validate examples/basic'
        working-directory: examples/basic
        run: |
          terraform init
          terraform validate
