name: Terraform CI - validate

on:
  [push]

jobs:
  tf_validate:
    name: 'Terraform validate (${{ matrix.terraform_version }})'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    strategy:
      matrix:
        terraform_version:
          - 1.10.5
          - 1.15.1
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: 'Terraform - validate examples/basic'
        working-directory: examples/basic
        run: |
          terraform init
          terraform validate
